# -*- coding: utf-8 -*-
"""
/***************************************************************************
 geo_value_functions
                                 A QGIS plugin
 Allows to apply a function to a raster or vector layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-09-07
        copyright            : (C) 2020 by LANCIS
        email                : serranoycandela@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load geo_value_functions class from file geo_value_functions.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geo_value_functions import geo_value_functions
    return geo_value_functions(iface)
